version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/sample-app"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
  - package-ecosystem: "docker"
    directory: "/sample-app"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
