---
# https://opentelemetry.io/docs/kubernetes/getting-started/#deployment-collector
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

replicaCount: 1

presets:
  clusterMetrics:
    enabled: true
  kubernetesEvents:
    enabled: true

config:
  exporters:
    prometheusremotewrite/mimir:
      endpoint: http://mimir-distributor.mimir:8080/api/v1/push
      resource_to_telemetry_conversion:
        enabled: true

  service:
    pipelines:
      metrics:
        exporters: [ prometheusremotewrite/mimir ]
