---
name: Release

on:
  release:
    types:
      - published
      - released

permissions:
  packages: write

jobs:
  TagEnv:
    name: "Update Image Tags"
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Env
        shell: bash
        run: |
          {
          echo "VERSION=${GITHUB_REF/refs\/tags\//}"
          } >> "$GITHUB_ENV"

      - uses: imjasonh/setup-crane@v0.4

      - name: Login GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image
        run: |
          crane tag "ghcr.io/${{ github.repository }}/sample-app:${{ github.sha }}" "ghcr.io/${{ github.repository }}/sample-app:${{ env.VERSION }}"
